sudo: required
dist: trusty
before_install:
- sudo apt-get -qq update && sudo apt-get install -y --no-install-recommends texlive-fonts-recommended
  texlive-latex-extra texlive-fonts-extra dvipng texlive-latex-recommended texlive-full
- sudo pip install Pygments
script:
  - cd doc
  - pdflatex -interaction=nonstopmode -shell-escape -halt-on-error eilar_thesis_2016.tex
  - bibtex eilar_thesis_2016.aux
  - pdflatex -interaction=nonstopmode -shell-escape -halt-on-error eilar_thesis_2016.tex
  - pdflatex -interaction=nonstopmode -shell-escape -halt-on-error eilar_thesis_2016.tex

before_deploy:
  - export RELEASE_FILE=$PWD/$(ls *.pdf)
  - echo "Current directory is $PWD"
  - echo The file is ${RELEASE_FILE}

deploy:
  provider: releases
  api_key:
    secure: WNz/OAV0KjmMxfwiJNsZPvu3ai+XVy+wBqUBSZI7b4jfR3P0bwNu6Ssks7mvKnVFuPnk5mLpfVT0g327y/+WIJVVfPLpfsVpL38mESZq7sRkvjO+oECkAELuGKZwYfuLDgLLxDAJedcjeoXyogJC92v5tAOHqxpj0SLYJOWaATA6JSx6j0Dw+4cM4L/ofsJ25WM4XkFLp91+3KRZyK2HJ1JvP3EncAzrKTZ98YqMcgwsT1aJ0KOTWQx55w9adou/Zl39q5tNpXWYZ0cZrC4LeoocZTE6cSWZf2a/PhLb8Kn05JcVG0FD68WrBtet2Ot1L+MAUOcB13V+z3fnGNxFrWZZuTWTHt1eMeiW6JmP90se4cJD8dHKQguUgkLTCvb/HUmSfrFt/m+kxxtsdBoZ8QVc8NsPQqJF+ob145ULqAcl3ztqMZQPLDIgf6bXEsuxJZ7fdHaP7r0m67H4jJVzhzVl1IVXPA55M0HyskVHFv398AmlKVRQhksbb5cs1oKBOUv/iw373scxj6EGlsUC6mMDcpTmHh5hns9hhnljxz+M209xicyQJJvq1ckipYaYzvAVzm1OAB/E4k8VZ44k9H7wzOoYuKEA+DgcutSkAoGBN0H6rjQge9y5udYrcUiQNpHk9jfyTvPo8eKfO50Ry7j3qBQhaH5umENTdppp5AU=
  file: ${RELEASE_FILE}
  on:
    branch: master
    repo: AcidLeroy/MastersThesis
